version: '3.10'
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: wordmasterdb
      MYSQL_USER: wordmaster
      MYSQL_PASSWORD: wordmaster123
      MYSQL_MAX_ALLOWED_PACKET: 128M
      TZ: UTC
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./mysql-init/schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - ./mysql-init/data.sql:/docker-entrypoint-initdb.d/3-data.sql
      - ./mysql-init/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - app-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --max_allowed_packet=128M
      --bind-address=0.0.0.0
      --secure-file-priv=/var/lib/mysql-files
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wordmaster", "-pwordmaster123"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wordmasterdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=wordmaster
      - SPRING_DATASOURCE_PASSWORD=wordmaster123
      - SERVER_SERVLET_CONTEXT_PATH=/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    restart: always
    environment:
      - BACKEND_API_URL=http://spring-backend:8080
      - NEXT_PUBLIC_API_URL=https://www.ingilizcem.net/api
      - NEXT_PUBLIC_FRONTEND_URL=https://www.ingilizcem.net
      - NEXTAUTH_URL=https://www.ingilizcem.net
      - NEXTAUTH_SECRET=NQOSd8J/wnueoxrzwc9BzoSfxvn5vvT9d+pGowghpUA=
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks: 
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email gurkay.basyigit@gmail.com -d ingilizcem.net -d www.ingilizcem.net --agree-tos

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge